name: new_flutterrrrr
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  salomon_bottom_bar: ^3.3.2
  google_fonts: ^6.2.1
  gradient_widgets: ^0.6.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - Assets/images/nike.svg
    - Assets/images/nikejpg.jpg
    - Assets/images/menu.svg
    - Assets/images/menuicon.svg
    - Assets/images/cartIcon.svg
    - Assets/images/firstshoepng.png
    - Assets/images/firstshoe.svg
    - Assets/images/secondshoe.svg
    - Assets/images/secondshoepng.png
    - Assets/images/thirdshoe.svg
    - Assets/images/thirdshoepng.png
    - Assets/images/plusicon.svg
    - Assets/images/plusiconpng.png
    - Assets/images/plusicongreen.svg
    - Assets/images/plusicongreenpng.png
    - Assets/images/plusiconbrown.svg
    - Assets/images/plusiconbrownpng.png
    - Assets/images/plusiconpurplepng.png
    - Assets/images/niketwogreenshoe.svg
    - Assets/images/niketwogreenshoepng.png
    - Assets/images/shoppingcart.svg
    - Assets/images/shoppingcartpng.png
    - Assets/images/shoppingcarticonblack.svg
    - Assets/images/shoppingcarticonblackpng.png
    - Assets/images/UserCircle.svg
    - Assets/photography/MagnifyingGlass.svg
    - Assets/photography/MagnifyingGlass.png
    - Assets/firstimage/baloonone.svg
    - Assets/firstimage/baloononepng.png
    - Assets/firstimage/baloontwo.svg
    - Assets/firstimage/baloontwopng.png
    - Assets/firstimage/guyonrocket.svg
    - Assets/firstimage/guyonrocketpng.png
    - Assets/firstimage/worldglobe.svg
    - Assets/firstimage/worldglobepng.png
    - Assets/firstimage/guyontricycle.svg
    - Assets/firstimage/guyontricyclepng.png
    - Assets/firstimage/welcomebackicon.svg
    - Assets/firstimage/welcomebackiconpng.png
    - Assets/firstimage/getstartedicon.svg
    - Assets/firstimage/getstartedpng.png
    - Assets/firstimage/line.svg
    - Assets/firstimage/linepng.png
    - Assets/firstimage/googleicon.svg
    - Assets/firstimage/googleiconpng.png
    - Assets/firstimage/facebookicon.svg
    - Assets/firstimage/facebookiconpng.png
    - Assets/firstimage/twittericon.svg
    - Assets/firstimage/twittericonpng.png
    - Assets/firstimage/icongoback.svg
    - Assets/firstimage/icongobackpng.png
    - Assets/firstimage/welcometohome.svg
    - Assets/firstimage/welcometohomepng.png
    - Assets/firstimage/loadingend.svg
    - Assets/firstimage/loadingendpng.png
    - Assets/firstimage/loadingfirst.svg
    - Assets/firstimage/loadingfirstpng.png
    - Assets/firstimage/loadingmiddle.svg
    - Assets/firstimage/loadingmiddlepng.png
    - Assets/photography/profilepicsamantha.svg
    - Assets/photography/profilepicsamanthajpg.jpg
    - Assets/photography/profilepicsamanthapng.png
    - Assets/photography/notificationicon.svg
    - Assets/photography/notificationiconpng.png
    - Assets/photography/wildlifephoto.svg
    - Assets/photography/wildlifephotopng.png
    - Assets/photography/wildlifephototwo.svg
    - Assets/photography/wildlifephototwopng.png
    - Assets/travelimage/screentwofirstpp.svg
    - Assets/travelimage/screentwofirstpppng.png
    - Assets/travelimage/screentwofirstpppngpng.jpg
    - Assets/travelimage/screentwosecondpp.svg
    - Assets/travelimage/screentwosecondpppng.png
    - Assets/travelimage/screentwosecondpppngpng.png
    - Assets/travelimage/screentwothirdpp.svg
    - Assets/travelimage/screentwothirdpppng.png
    - Assets/travelimage/screentwofourthpp.svg
    - Assets/travelimage/screentwofourthpppng.png
    - Assets/travelimage/screentwofifthpp.svg
    - Assets/travelimage/screentwofifthpppng.png
    - Assets/travelimage/screentwofifthpppngpng.png
    - Assets/travelimage/coverscreentwo.svg
    - Assets/travelimage/coverscreentwopng.png
    - Assets/travelimage/coverscreentwopngpng.png
    - Assets/travelimage/avatarprofilepic.svg
    - Assets/travelimage/avatarprofilepicpng.png
    - Assets/travelimage/travelscreenonepic.svg
    - Assets/travelimage/travelscreenonepicpng.png
    - Assets/travelimage/travelscreentwopic.svg
    - Assets/travelimage/travelscreentwopicpng.png
    - Assets/travelimage/profilepicPeace.svg
    - Assets/travelimage/profilepicPeacepng.png
    - Assets/travelimage/profilepicPeacepngpng.png
    - Assets/travelimage/screenthreecover.svg
    - Assets/travelimage/screenthreecoverjpg.jpg
    - Assets/travelimage/screenthreecoverpng.png
    - Assets/travelimage/screenthreecovertwopng.png
    - Assets/travelimage/Menu (1).svg
    - Assets/travelimage/Menu.png
    - Assets/travelimage/Frame 40.svg
    - Assets/travelimage/Frame 36.svg
    - Assets/travelimage/Frame 37.svg
    - Assets/travelimage/Search icon.svg
    - Assets/travelimage/Search icon.png
    - Assets/travelimage/Frame 25.svg
    - Assets/photography/shape.svg
    - Assets/photography/search 1.svg
    - Assets/photography/shape.png
    - Assets/photography/search.png
    - Assets/photography/calendar.svg
    - Assets/photography/calendarpng.png
    - Assets/photography/chaticon.svg
    - Assets/photography/chaticonpng.png
    - Assets/travelimage/Star Copy 6.svg

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
